//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BadgES.Module.BusinessObjects.BadgES
{

    public partial class DetailedRaw : XPLiteObject
    {
        int fxrowid;
        [Key(true)]
        public int xrowid
        {
            get { return fxrowid; }
            set { SetPropertyValue<int>(nameof(xrowid), ref fxrowid, value); }
        }
        ResourceList fKeyLink;
        [ColumnDbDefaultValue("((-1))")]
        [Association(@"DetailedRawReferencesResourceList")]
        public ResourceList KeyLink
        {
            get { return fKeyLink; }
            set { SetPropertyValue<ResourceList>(nameof(KeyLink), ref fKeyLink, value); }
        }
        string fLoadId;
        [Size(50)]
        public string LoadId
        {
            get { return fLoadId; }
            set { SetPropertyValue<string>(nameof(LoadId), ref fLoadId, value); }
        }
        string fDateTime;
        [Size(50)]
        public string DateTime
        {
            get { return fDateTime; }
            set { SetPropertyValue<string>(nameof(DateTime), ref fDateTime, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fCardNo;
        [Size(50)]
        public string CardNo
        {
            get { return fCardNo; }
            set { SetPropertyValue<string>(nameof(CardNo), ref fCardNo, value); }
        }
        string fDoorLocation;
        [Size(50)]
        public string DoorLocation
        {
            get { return fDoorLocation; }
            set { SetPropertyValue<string>(nameof(DoorLocation), ref fDoorLocation, value); }
        }
        string fTransactionType;
        [Size(50)]
        public string TransactionType
        {
            get { return fTransactionType; }
            set { SetPropertyValue<string>(nameof(TransactionType), ref fTransactionType, value); }
        }
        string fOfficeLocation;
        [Size(50)]
        public string OfficeLocation
        {
            get { return fOfficeLocation; }
            set { SetPropertyValue<string>(nameof(OfficeLocation), ref fOfficeLocation, value); }
        }
        string fDetail;
        [Size(50)]
        public string Detail
        {
            get { return fDetail; }
            set { SetPropertyValue<string>(nameof(Detail), ref fDetail, value); }
        }
    }

}
