//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BadgES.Module.BusinessObjects.BadgES
{

    public partial class ResourceList : XPLiteObject
    {
        int fKeyLink;
        [Key(true)]
        public int KeyLink
        {
            get { return fKeyLink; }
            set { SetPropertyValue<int>(nameof(KeyLink), ref fKeyLink, value); }
        }
        string fResourceQlid;
        [Size(50)]
        public string ResourceQlid
        {
            get { return fResourceQlid; }
            set { SetPropertyValue<string>(nameof(ResourceQlid), ref fResourceQlid, value); }
        }
        string fResourceName;
        [Indexed(Name = @"UQ__Resource__737584F6C1716C63", Unique = true)]
        [Size(50)]
        public string ResourceName
        {
            get { return fResourceName; }
            set { SetPropertyValue<string>(nameof(ResourceName), ref fResourceName, value); }
        }
        string fManagerQlid;
        [Size(50)]
        public string ManagerQlid
        {
            get { return fManagerQlid; }
            set { SetPropertyValue<string>(nameof(ManagerQlid), ref fManagerQlid, value); }
        }
        string fManagerName;
        [Size(50)]
        public string ManagerName
        {
            get { return fManagerName; }
            set { SetPropertyValue<string>(nameof(ManagerName), ref fManagerName, value); }
        }
        string fOnsiteFlag;
        [Size(50)]
        public string OnsiteFlag
        {
            get { return fOnsiteFlag; }
            set { SetPropertyValue<string>(nameof(OnsiteFlag), ref fOnsiteFlag, value); }
        }
        [Association(@"DetailedEntryExitPairReferencesResourceList")]
        public XPCollection<DetailedEntryExitPair> DetailedEntryExitPairs { get { return GetCollection<DetailedEntryExitPair>(nameof(DetailedEntryExitPairs)); } }
        [Association(@"DetailedRawReferencesResourceList")]
        public XPCollection<DetailedRaw> DetailedRaws { get { return GetCollection<DetailedRaw>(nameof(DetailedRaws)); } }
        [Association(@"SummaryReferencesResourceList")]
        public XPCollection<Summary> Summaries { get { return GetCollection<Summary>(nameof(Summaries)); } }
    }

}
