//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BadgES.Module.BusinessObjects.BadgES
{

    public partial class Summary : XPLiteObject
    {
        int fxrowid;
        [Key(true)]
        public int xrowid
        {
            get { return fxrowid; }
            set { SetPropertyValue<int>(nameof(xrowid), ref fxrowid, value); }
        }
        ResourceList fKeyLink;
        [ColumnDbDefaultValue("((-1))")]
        [Association(@"SummaryReferencesResourceList")]
        public ResourceList KeyLink
        {
            get { return fKeyLink; }
            set { SetPropertyValue<ResourceList>(nameof(KeyLink), ref fKeyLink, value); }
        }
        string fRowId;
        [Size(50)]
        public string RowId
        {
            get { return fRowId; }
            set { SetPropertyValue<string>(nameof(RowId), ref fRowId, value); }
        }
        string fQuicklookId;
        [Size(50)]
        public string QuicklookId
        {
            get { return fQuicklookId; }
            set { SetPropertyValue<string>(nameof(QuicklookId), ref fQuicklookId, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fCardNo;
        [Size(50)]
        public string CardNo
        {
            get { return fCardNo; }
            set { SetPropertyValue<string>(nameof(CardNo), ref fCardNo, value); }
        }
        string fFirstIn;
        [Size(50)]
        public string FirstIn
        {
            get { return fFirstIn; }
            set { SetPropertyValue<string>(nameof(FirstIn), ref fFirstIn, value); }
        }
        string fLastOut;
        [Size(50)]
        public string LastOut
        {
            get { return fLastOut; }
            set { SetPropertyValue<string>(nameof(LastOut), ref fLastOut, value); }
        }
        string fWorkHours;
        [Size(50)]
        public string WorkHours
        {
            get { return fWorkHours; }
            set { SetPropertyValue<string>(nameof(WorkHours), ref fWorkHours, value); }
        }
        string fOvertime;
        [Size(50)]
        public string Overtime
        {
            get { return fOvertime; }
            set { SetPropertyValue<string>(nameof(Overtime), ref fOvertime, value); }
        }
        string fMealAllowance;
        [Size(50)]
        public string MealAllowance
        {
            get { return fMealAllowance; }
            set { SetPropertyValue<string>(nameof(MealAllowance), ref fMealAllowance, value); }
        }
        string fTranspoAllowance;
        [Size(50)]
        public string TranspoAllowance
        {
            get { return fTranspoAllowance; }
            set { SetPropertyValue<string>(nameof(TranspoAllowance), ref fTranspoAllowance, value); }
        }
        string fPremiumPay;
        [Size(50)]
        public string PremiumPay
        {
            get { return fPremiumPay; }
            set { SetPropertyValue<string>(nameof(PremiumPay), ref fPremiumPay, value); }
        }
        string fPremiumHoursWorked;
        [Size(50)]
        public string PremiumHoursWorked
        {
            get { return fPremiumHoursWorked; }
            set { SetPropertyValue<string>(nameof(PremiumHoursWorked), ref fPremiumHoursWorked, value); }
        }
        string fPremiumHoursInOffice;
        [Size(50)]
        public string PremiumHoursInOffice
        {
            get { return fPremiumHoursInOffice; }
            set { SetPropertyValue<string>(nameof(PremiumHoursInOffice), ref fPremiumHoursInOffice, value); }
        }
    }

}
